In [ ]:
## Name: Frenel Cherubin
## Date: 1/19/2020
## Course DSC 540
## Assignment: Midterm Project

In [ ]:
# The following is due submitted to the assignment link
# or submit a link to your GitHub repository to the assignment link:
# Your dataset with the following transformations

In [ ]:
# Replace headers (Data Wrangling with Python pg. 154 â€“ 163)

In [19]:
# loading the required libraries and the data
# Import required libraries
from csv import DictReader 
# DictReader reads in the first line of the CSV and using each comma separated value in this line as a dictionary key. 
data_rdr = DictReader(open('GO.csv', 'r'))
header_rdr = DictReader(open('GO.csv', 'r', encoding = "utf8"))

In [20]:
data_rows = [d for d in data_rdr]
header_rows = [h for h in header_rdr]

In [21]:
data_rows[0]

OrderedDict([('Cohort Year', '2001'),
             ('Cohort Category', '4 Year  June'),
             ('Demographic', 'English Language Learner'),
             ('# Total Cohort', '10540'),
             ('# Total Grads', '2791'),
             ('% of cohort Total Grads', '26.5'),
             ('# of cohort Total Grads', '992'),
             ('% of cohort Total Regents', '9'),
             ('% of grads  Total Regents', '35.5'),
             ('# of grads  Total Regents', '315'),
             ('% of cohort  Advanced Regents', '3'),
             ('% of grads  Advanced Regents', '11.3'),
             ('# of grads  Advanced Regents', '677'),
             ('% of cohort  Regents w/o Advanced', '6.4'),
             ('% of grads  Regents w/o Advanced', '24.3'),
             ('# of grads  Regents w/o Advanced', '1803'),
             ('% of cohort Local', '17.1'),
             ('% of grads Local', '64.6'),
             ('# Still Enrolled', '3895'),
             ('% of cohort Still Enrolled', '37'),
             ('# Dropped Out', '3220'),
             ('% of cohort Dropped Out', '30.6')])

In [22]:
# Create new rows
new_rows = []

for data_dict in data_rows:
    new_row = {}
    for dkey, dval in data_dict.items():
        for header_dict in header_rows:
            if dkey in header_dict.values():
                new_row[header_dict.get('Label')] = dval
    new_rows.append(new_row)

In [23]:
# Create header rows
header_rows[0:5]

[OrderedDict([('Cohort Year', '2001'),
              ('Cohort Category', '4 Year  June'),
              ('Demographic', 'English Language Learner'),
              ('# Total Cohort', '10540'),
              ('# Total Grads', '2791'),
              ('% of cohort Total Grads', '26.5'),
              ('# of cohort Total Grads', '992'),
              ('% of cohort Total Regents', '9'),
              ('% of grads  Total Regents', '35.5'),
              ('# of grads  Total Regents', '315'),
              ('% of cohort  Advanced Regents', '3'),
              ('% of grads  Advanced Regents', '11.3'),
              ('# of grads  Advanced Regents', '677'),
              ('% of cohort  Regents w/o Advanced', '6.4'),
              ('% of grads  Regents w/o Advanced', '24.3'),
              ('# of grads  Regents w/o Advanced', '1803'),
              ('% of cohort Local', '17.1'),
              ('% of grads Local', '64.6'),
              ('# Still Enrolled', '3895'),
              ('% of cohort Still Enrolled', '37'),
              ('# Dropped Out', '3220'),
              ('% of cohort Dropped Out', '30.6')]),
 OrderedDict([('Cohort Year', '2001'),
              ('Cohort Category', '5 Year  June'),
              ('Demographic', 'English Language Learner'),
              ('# Total Cohort', '10540'),
              ('# Total Grads', '3920'),
              ('% of cohort Total Grads', '37.2'),
              ('# of cohort Total Grads', '1233'),
              ('% of cohort Total Regents', '11.7'),
              ('% of grads  Total Regents', '31.5'),
              ('# of grads  Total Regents', '371'),
              ('% of cohort  Advanced Regents', '3.5'),
              ('% of grads  Advanced Regents', '9.5'),
              ('# of grads  Advanced Regents', '862'),
              ('% of cohort  Regents w/o Advanced', '8.2'),
              ('% of grads  Regents w/o Advanced', '22'),
              ('# of grads  Regents w/o Advanced', '2701'),
              ('% of cohort Local', '25.6'),
              ('% of grads Local', '68.9'),
              ('# Still Enrolled', '1516'),
              ('% of cohort Still Enrolled', '14.4'),
              ('# Dropped Out', '4193'),
              ('% of cohort Dropped Out', '39.8')]),
 OrderedDict([('Cohort Year', '2001'),
              ('Cohort Category', '6 Year'),
              ('Demographic', 'English Language Learner'),
              ('# Total Cohort', '10540'),
              ('# Total Grads', '4296'),
              ('% of cohort Total Grads', '40.8'),
              ('# of cohort Total Grads', '1291'),
              ('% of cohort Total Regents', '12.2'),
              ('% of grads  Total Regents', '30.1'),
              ('# of grads  Total Regents', '380'),
              ('% of cohort  Advanced Regents', '3.6'),
              ('% of grads  Advanced Regents', '8.8'),
              ('# of grads  Advanced Regents', '911'),
              ('% of cohort  Regents w/o Advanced', '8.6'),
              ('% of grads  Regents w/o Advanced', '21.2'),
              ('# of grads  Regents w/o Advanced', '3028'),
              ('% of cohort Local', '28.7'),
              ('% of grads Local', '70.5'),
              ('# Still Enrolled', '655'),
              ('% of cohort Still Enrolled', '6.2'),
              ('# Dropped Out', '4598'),
              ('% of cohort Dropped Out', '43.6')]),
 OrderedDict([('Cohort Year', '2002'),
              ('Cohort Category', '4 Year  June'),
              ('Demographic', 'English Language Learner'),
              ('# Total Cohort', '7454'),
              ('# Total Grads', '1691'),
              ('% of cohort Total Grads', '22.7'),
              ('# of cohort Total Grads', '639'),
              ('% of cohort Total Regents', '8.6'),
              ('% of grads  Total Regents', '37.8'),
              ('# of grads  Total Regents', '132'),
              ('% of cohort  Advanced Regents', '1.8'),
              ('% of grads  Advanced Regents', '7.8'),
              ('# of grads  Advanced Regents', '507'),
              ('% of cohort  Regents w/o Advanced', '6.8'),
              ('% of grads  Regents w/o Advanced', '30'),
              ('# of grads  Regents w/o Advanced', '1062'),
              ('% of cohort Local', '14.2'),
              ('% of grads Local', '62.8'),
              ('# Still Enrolled', '3062'),
              ('% of cohort Still Enrolled', '41.1'),
              ('# Dropped Out', '2330'),
              ('% of cohort Dropped Out', '31.3')]),
 OrderedDict([('Cohort Year', '2002'),
              ('Cohort Category', '5 Year  June'),
              ('Demographic', 'English Language Learner'),
              ('# Total Cohort', '7454'),
              ('# Total Grads', '2354'),
              ('% of cohort Total Grads', '31.6'),
              ('# of cohort Total Grads', '794'),
              ('% of cohort Total Regents', '10.7'),
              ('% of grads  Total Regents', '33.7'),
              ('# of grads  Total Regents', '176'),
              ('% of cohort  Advanced Regents', '2.4'),
              ('% of grads  Advanced Regents', '7.5'),
              ('# of grads  Advanced Regents', '618'),
              ('% of cohort  Regents w/o Advanced', '8.3'),
              ('% of grads  Regents w/o Advanced', '26.3'),
              ('# of grads  Regents w/o Advanced', '1578'),
              ('% of cohort Local', '21.2'),
              ('% of grads Local', '67'),
              ('# Still Enrolled', '1457'),
              ('% of cohort Still Enrolled', '19.5'),
              ('# Dropped Out', '3041'),
              ('% of cohort Dropped Out', '40.8')])]

In [24]:
new_rows[0]

{}

In [ ]:
# Format Data to a Readable Format (Data Wrangling with Python pg. 164 â€“ 168)

In [25]:
# Create a for loop that itirates through the list to return the values in the dictionary.
for dkey, dval in new_rows[0].items():
    print('Question: {}\nAnswer: {}'.format(dkey, dval))

In [26]:
# Import required libraries
from csv import reader

# The reader method returns a reader object which iterates over lines in the file, so its contents can be written
# and read.
data_rdr = reader(open('GO.csv', 'r'))
header_rdr = reader(open('GO.csv', 'r', encoding = "utf8"))

data_rows = [d for d in data_rdr]
header_rows = [h for h in header_rdr if h[0] in data_rows[0]]

all_short_headers = [h[0] for h in header_rows]
skip_index = []
final_header_rows = []

# Create a for loop that itirates through the list to return the values in a dictionary
for header in data_rows[0]:
# # Invoke if/else as conditional statements.
    if header not in all_short_headers:
        index = data_rows[0].index(header)
        skip_index.append(index)
    else:
        for head in header_rows:
            if head[0] == header:
                final_header_rows.append(head)
                break

del all_short_headers
new_data = []
for row in data_rows[1:]:
    new_row = []
    for i, d in enumerate(row):
        if i not in skip_index:
            new_row.append(d)
        new_data.append(new_row)


zipped_data = []
for drow in new_data:
    zipped_data.append(zip(header_rows, drow))

In [27]:
# Create a for loop that itirates through the list and returns the values.
for value1, value2 in zipped_data[0]:
    print('Question: {}\nAnswer: {}'.format(value1[0:2], value2))

Question: ['Cohort Year', 'Cohort Category']
Answer: 2001

In [ ]:
# Identify outliers and bad data (Data Wrangling with Python pg. 169 â€“ 174)

In [28]:
# loading the required libraries and the data
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# Reading the data
df = pd.read_csv('GO.csv')
print(df.shape)
print(df.info())

(430, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 22 columns):
Cohort Year                          430 non-null int64
Cohort Category                      430 non-null object
Demographic                          430 non-null object
# Total Cohort                       430 non-null int64
# Total Grads                        430 non-null int64
% of cohort Total Grads              430 non-null float64
# of cohort Total Grads              430 non-null int64
% of cohort Total Regents            430 non-null float64
% of grads  Total Regents            430 non-null float64
# of grads  Total Regents            420 non-null float64
% of cohort  Advanced Regents        420 non-null float64
% of grads  Advanced Regents         420 non-null float64
# of grads  Advanced Regents         420 non-null float64
% of cohort  Regents w/o Advanced    420 non-null float64
% of grads  Regents w/o Advanced     420 non-null float64
# of grads  Regents w/o Advanced     430 non-null int64
% of cohort Local                    430 non-null float64
% of grads Local                     430 non-null float64
# Still Enrolled                     430 non-null int64
% of cohort Still Enrolled           430 non-null float64
# Dropped Out                        430 non-null int64
% of cohort Dropped Out              430 non-null float64
dtypes: float64(13), int64(7), object(2)
memory usage: 74.0+ KB
None

In [ ]:
# In the dataset, there are 430 observations of 22 variables. All of the variables have 430 records. This indicates
# that the data has no missing value.

In [29]:
# Identify Outliers
df.describe()

,Cohort Year,# Total Cohort,# Total Grads,% of cohort Total Grads,# of cohort Total Grads,% of cohort Total Regents,% of grads Total Regents,# of grads Total Regents,% of cohort Advanced Regents,% of grads Advanced Regents,# of grads Advanced Regents,% of cohort Regents w/o Advanced,% of grads Regents w/o Advanced,# of grads Regents w/o Advanced,% of cohort Local,% of grads Local,# Still Enrolled,% of cohort Still Enrolled,# Dropped Out,% of cohort Dropped Out
count,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000
mean,2006.186047,30728.830233,20082.302326,62.319767,16250.748837,49.482558,75.448140,5002.169048,16.532143,23.751190,11331.492857,33.167381,51.925476,3839.400000,12.860233,24.601163,4519.990698,15.620930,5014.179070,17.383721
std,2.866540,21193.889781,15423.868054,16.013714,13673.310038,20.837416,20.221693,4220.128136,12.296028,14.100374,9898.656051,13.379219,16.030910,3869.125207,8.209207,20.282238,4150.879411,10.555136,3673.011177,8.034310
min,2001.000000,6974.000000,1287.000000,17.100000,256.000000,2.900000,13.800000,35.000000,0.400000,1.900000,218.000000,2.300000,11.900000,117.000000,0.600000,0.800000,129.000000,1.100000,513.000000,4.600000
25%,2004.000000,10821.500000,7944.250000,52.975000,6456.500000,35.700000,63.875000,1626.750000,7.000000,13.000000,3231.250000,23.475000,40.350000,1144.750000,4.700000,7.425000,1547.500000,6.800000,2071.250000,10.900000
50%,2006.000000,26626.000000,16168.000000,65.450000,12180.500000,52.350000,80.700000,3343.000000,14.900000,24.250000,8880.000000,33.650000,48.850000,2101.000000,13.250000,19.300000,3105.500000,12.450000,4156.500000,16.000000
75%,2009.000000,39287.250000,27429.250000,75.200000,23951.500000,65.625000,92.575000,7120.000000,19.600000,28.225000,16572.250000,44.150000,67.725000,5817.750000,19.175000,36.300000,6599.500000,22.700000,7075.250000,21.600000
max,2011.000000,70545.000000,53974.000000,87.700000,52374.000000,85.500000,99.200000,13479.000000,47.100000,58.600000,38895.000000,58.100000,82.500000,17392.000000,30.400000,86.900000,18972.000000,48.300000,19482.000000,45.000000

In [ ]:
# There is a lot of outliers when looking at the variables. Outliers are in % of cohort Total Regents,
# # of grads Total Regents, % of cohort Advanced Regents, and so forth as a result of incorrect data.
# I choose # of grads Total Regents variable as the focus of outliers detection.
# In the # of grads Total Regents variable, the minimun and maximum numbers of grads total regents are 35 and
# 13479 respectively.

In [30]:
# Identifying Outliers with Interquartile Range (IQR)
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
print(IQR)
# The output will print the IQR scores, which can be used to detect outliers.

Cohort Year                              5.000
# Total Cohort                       28465.750
# Total Grads                        19485.000
% of cohort Total Grads                 22.225
# of cohort Total Grads              17495.000
% of cohort Total Regents               29.925
% of grads  Total Regents               28.700
# of grads  Total Regents             5493.250
% of cohort  Advanced Regents           12.600
% of grads  Advanced Regents            15.225
# of grads  Advanced Regents         13341.000
% of cohort  Regents w/o Advanced       20.675
% of grads  Regents w/o Advanced        27.375
# of grads  Regents w/o Advanced      4673.000
% of cohort Local                       14.475
% of grads Local                        28.875
# Still Enrolled                      5052.000
% of cohort Still Enrolled              15.900
# Dropped Out                         5004.000
% of cohort Dropped Out                 10.700
dtype: float64

In [31]:
# Determining points that indicates the presence ot outliers where a true value is a positive test for outliers.
print(df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))

     # Dropped Out  # Still Enrolled  # Total Cohort  # Total Grads  \
0            False             False           False          False
1            False             False           False          False
2            False             False           False          False
3            False             False           False          False
4            False             False           False          False
5            False             False           False          False
6            False             False           False          False
7            False             False           False          False
8            False             False           False          False
9            False             False           False          False
10           False             False           False          False
11           False             False           False          False
12           False             False           False          False
13           False             False           False          False
14           False             False           False          False
15           False             False           False          False
16           False             False           False          False
17           False             False           False          False
18           False             False           False          False
19           False             False           False          False
20           False             False           False          False
21           False             False           False          False
22           False             False           False          False
23           False             False           False          False
24           False             False           False          False
25           False             False           False          False
26           False             False           False          False
27           False             False           False          False
28           False             False           False          False
29           False             False           False          False
..             ...               ...             ...            ...
400          False             False           False          False
401          False             False           False          False
402          False             False           False          False
403          False             False           False          False
404          False             False           False          False
405          False             False           False          False
406          False             False           False          False
407          False             False           False          False
408          False             False           False          False
409          False             False           False          False
410          False             False           False          False
411          False             False           False          False
412          False             False           False          False
413          False             False           False          False
414          False             False           False          False
415          False             False           False          False
416          False             False           False          False
417          False             False           False          False
418          False             False           False          False
419          False             False           False          False
420          False             False           False          False
421          False             False           False          False
422          False             False           False          False
423          False             False           False          False
424          False             False           False          False
425          False             False           False          False
426          False             False           False          False
427          False             False           False          False
428          False             False           False          False
429          False             False           False          False

     # of cohort Total Grads  # of grads  Advanced Regents  \
0                      False                         False
1                      False                         False
2                      False                         False
3                      False                         False
4                      False                         False
5                      False                         False
6                      False                         False
7                      False                         False
8                      False                         False
9                      False                         False
10                     False                         False
11                     False                         False
12                     False                         False
13                     False                         False
14                     False                         False
15                     False                         False
16                     False                         False
17                     False                         False
18                     False                         False
19                     False                         False
20                     False                         False
21                     False                         False
22                     False                         False
23                     False                         False
24                     False                         False
25                     False                         False
26                     False                         False
27                     False                         False
28                     False                         False
29                     False                         False
..                       ...                           ...
400                    False                         False
401                    False                         False
402                    False                         False
403                    False                         False
404                    False                         False
405                    False                         False
406                    False                         False
407                    False                         False
408                    False                         False
409                    False                         False
410                    False                         False
411                    False                         False
412                    False                         False
413                    False                         False
414                    False                         False
415                    False                         False
416                    False                         False
417                    False                         False
418                    False                         False
419                    False                         False
420                    False                         False
421                    False                         False
422                    False                         False
423                    False                         False
424                    False                         False
425                    False                         False
426                    False                         False
427                    False                         False
428                    False                         False
429                    False                         False

     # of grads  Regents w/o Advanced  # of grads  Total Regents  \
0                               False                      False
1                               False                      False
2                               False                      False
3                               False                      False
4                               False                      False
5                               False                      False
6                               False                      False
7                               False                      False
8                               False                      False
9                               False                      False
10                              False                      False
11                              False                      False
12                              False                      False
13                              False                      False
14                              False                      False
15                              False                      False
16                              False                      False
17                              False                      False
18                              False                      False
19                              False                      False
20                              False                      False
21                              False                      False
22                              False                      False
23                              False                      False
24                              False                      False
25                              False                      False
26                              False                      False
27                              False                      False
28                              False                      False
29                              False                      False
..                                ...                        ...
400                             False                      False
401                             False                      False
402                             False                      False
403                             False                      False
404                             False                      False
405                             False                      False
406                             False                      False
407                             False                      False
408                             False                      False
409                             False                      False
410                             False                      False
411                             False                      False
412                             False                      False
413                             False                      False
414                             False                      False
415                             False                      False
416                             False                      False
417                             False                      False
418                             False                      False
419                             False                      False
420                             False                      False
421                             False                      False
422                             False                      False
423                             False                      False
424                             False                      False
425                             False                      False
426                             False                      False
427                             False                      False
428                             False                      False
429                             False                      False

     % of cohort  Advanced Regents  % of cohort  Regents w/o Advanced  ...  \
0                            False                              False  ...
1                            False                              False  ...
2                            False                              False  ...
3                            False                              False  ...
4                            False                              False  ...
5                            False                              False  ...
6                            False                              False  ...
7                            False                              False  ...
8                            False                              False  ...
9                            False                              False  ...
10                           False                              False  ...
11                           False                              False  ...
12                           False                              False  ...
13                           False                              False  ...
14                           False                              False  ...
15                           False                              False  ...
16                           False                              False  ...
17                           False                              False  ...
18                           False                              False  ...
19                           False                              False  ...
20                           False                              False  ...
21                           False                              False  ...
22                           False                              False  ...
23                           False                              False  ...
24                           False                              False  ...
25                           False                              False  ...
26                           False                              False  ...
27                           False                              False  ...
28                           False                              False  ...
29                           False                              False  ...
..                             ...                                ...  ...
400                          False                              False  ...
401                          False                              False  ...
402                          False                              False  ...
403                          False                              False  ...
404                          False                              False  ...
405                          False                              False  ...
406                          False                              False  ...
407                          False                              False  ...
408                          False                              False  ...
409                          False                              False  ...
410                          False                              False  ...
411                          False                              False  ...
412                          False                              False  ...
413                          False                              False  ...
414                          False                              False  ...
415                          False                              False  ...
416                          False                              False  ...
417                          False                              False  ...
418                          False                              False  ...
419                          False                              False  ...
420                          False                              False  ...
421                          False                              False  ...
422                          False                              False  ...
423                          False                              False  ...
424                          False                              False  ...
425                          False                              False  ...
426                          False                              False  ...
427                          False                              False  ...
428                          False                              False  ...
429                          False                              False  ...

     % of cohort Still Enrolled  % of cohort Total Grads  \
0                         False                    False
1                         False                    False
2                         False                    False
3                         False                    False
4                         False                    False
5                         False                    False
6                         False                    False
7                         False                    False
8                         False                    False
9                         False                    False
10                        False                    False
11                        False                    False
12                        False                    False
13                        False                    False
14                        False                    False
15                        False                    False
16                        False                    False
17                        False                    False
18                        False                    False
19                        False                    False
20                        False                    False
21                        False                    False
22                        False                    False
23                        False                    False
24                        False                    False
25                        False                    False
26                        False                    False
27                        False                    False
28                        False                    False
29                        False                    False
..                          ...                      ...
400                       False                    False
401                       False                    False
402                       False                    False
403                       False                    False
404                       False                    False
405                       False                    False
406                       False                    False
407                       False                    False
408                       False                    False
409                       False                    False
410                       False                    False
411                       False                    False
412                       False                    False
413                       False                    False
414                       False                    False
415                       False                    False
416                       False                    False
417                       False                    False
418                       False                    False
419                       False                    False
420                       False                    False
421                       False                    False
422                       False                    False
423                       False                    False
424                       False                    False
425                       False                    False
426                       False                    False
427                       False                    False

TypeError: cannot compare a dtyped [bool] array with a scalar of type [NoneType]

In [32]:
# Fixing outliers- Techhniques like Quantile-based Flooring and Capping,Trimming, IQR Score,
# Log Transformation, and so forth are used to treat outliers.

# Fixing outliers using the IQR Score technique. Anuthing that does not fall in range (Q1 - 1.5 IQR) and (Q3 + 1.5 IQR)
# is an outlier, and it can be removed.
df_out = df[~((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
print(df_out.shape)

(332, 22)

In [ ]:
# The initial dataset was 430 observations of 22 variales. The IQR Score outliers removal technique returns
# 332 observations of 22 variables. This indicates that a lot of records get deleted if the IQR method is used.

In [ ]:
# Find Duplicates (Data Wrangling with Python pg. 175 â€“ 178)

In [3]:
# loading the required libraries and the data
# Import required libraries
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('GO.csv')

In [34]:
df.head()

,Cohort Year,Cohort Category,Demographic,# Total Cohort,# Total Grads,% of cohort Total Grads,# of cohort Total Grads,% of cohort Total Regents,% of grads Total Regents,# of grads Total Regents,...,# of grads Advanced Regents,% of cohort Regents w/o Advanced,% of grads Regents w/o Advanced,# of grads Regents w/o Advanced,% of cohort Local,% of grads Local,# Still Enrolled,% of cohort Still Enrolled,# Dropped Out,% of cohort Dropped Out
0,2001,4 Year June,English Language Learner,10540,2791,26.5,992,9.0,35.5,315.0,...,677.0,6.4,24.3,1803,17.1,64.6,3895,37.0,3220,30.6
1,2001,5 Year June,English Language Learner,10540,3920,37.2,1233,11.7,31.5,371.0,...,862.0,8.2,22.0,2701,25.6,68.9,1516,14.4,4193,39.8
2,2001,6 Year,English Language Learner,10540,4296,40.8,1291,12.2,30.1,380.0,...,911.0,8.6,21.2,3028,28.7,70.5,655,6.2,4598,43.6
3,2002,4 Year June,English Language Learner,7454,1691,22.7,639,8.6,37.8,132.0,...,507.0,6.8,30.0,1062,14.2,62.8,3062,41.1,2330,31.3
4,2002,5 Year June,English Language Learner,7454,2354,31.6,794,10.7,33.7,176.0,...,618.0,8.3,26.3,1578,21.2,67.0,1457,19.5,3041,40.8

In [8]:
df.columns

Index(['Cohort Year', 'Cohort Category', 'Demographic', '# Total Cohort',
       '# Total Grads', '% of cohort Total Grads', '# of cohort Total Grads',
       '% of cohort Total Regents', '% of grads  Total Regents',
       '# of grads  Total Regents', '% of cohort  Advanced Regents',
       '% of grads  Advanced Regents', '# of grads  Advanced Regents',
       '% of cohort  Regents w/o Advanced', '% of grads  Regents w/o Advanced',
       '# of grads  Regents w/o Advanced', '% of cohort Local',
       '% of grads Local', '# Still Enrolled', '% of cohort Still Enrolled',
       '# Dropped Out', '% of cohort Dropped Out'],
      dtype='object')

In [35]:
# Change the columns to upper cases to make the data consistent.
df.columns.str.upper()

Index(['COHORT YEAR', 'COHORT CATEGORY', 'DEMOGRAPHIC', '# TOTAL COHORT',
       '# TOTAL GRADS', '% OF COHORT TOTAL GRADS', '# OF COHORT TOTAL GRADS',
       '% OF COHORT TOTAL REGENTS', '% OF GRADS  TOTAL REGENTS',
       '# OF GRADS  TOTAL REGENTS', '% OF COHORT  ADVANCED REGENTS',
       '% OF GRADS  ADVANCED REGENTS', '# OF GRADS  ADVANCED REGENTS',
       '% OF COHORT  REGENTS W/O ADVANCED', '% OF GRADS  REGENTS W/O ADVANCED',
       '# OF GRADS  REGENTS W/O ADVANCED', '% OF COHORT LOCAL',
       '% OF GRADS LOCAL', '# STILL ENROLLED', '% OF COHORT STILL ENROLLED',
       '# DROPPED OUT', '% OF COHORT DROPPED OUT'],
      dtype='object')

In [36]:
# Check for missing data. With false indicates the presence of data and true indicates the absence of data.
df.isnull()

,Cohort Year,Cohort Category,Demographic,# Total Cohort,# Total Grads,% of cohort Total Grads,# of cohort Total Grads,% of cohort Total Regents,% of grads Total Regents,# of grads Total Regents,...,# of grads Advanced Regents,% of cohort Regents w/o Advanced,% of grads Regents w/o Advanced,# of grads Regents w/o Advanced,% of cohort Local,% of grads Local,# Still Enrolled,% of cohort Still Enrolled,# Dropped Out,% of cohort Dropped Out
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,True,...,True,True,True,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
401,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
402,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
403,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
404,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
405,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
406,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
407,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
408,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
409,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
410,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
411,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
412,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
413,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
414,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
416,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
417,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
418,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
419,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
420,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
421,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
422,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
423,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
424,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
425,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
426,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
427,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
428,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
429,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [37]:
# The script below indicates the missing values in the entire dataset
df.isnull().any()

Cohort Year                          False
Cohort Category                      False
Demographic                          False
# Total Cohort                       False
# Total Grads                        False
% of cohort Total Grads              False
# of cohort Total Grads              False
% of cohort Total Regents            False
% of grads  Total Regents            False
# of grads  Total Regents             True
% of cohort  Advanced Regents         True
% of grads  Advanced Regents          True
# of grads  Advanced Regents          True
% of cohort  Regents w/o Advanced     True
% of grads  Regents w/o Advanced      True
# of grads  Regents w/o Advanced     False
% of cohort Local                    False
% of grads Local                     False
# Still Enrolled                     False
% of cohort Still Enrolled           False
# Dropped Out                        False
% of cohort Dropped Out              False
dtype: bool

In [38]:
# Columns with NAN using True/False
# False means it does not have a NAN.
df.isnull().any().any()

True

In [13]:
# columns with NAN using interger
df.isnull().sum()

Cohort Year                           0
Cohort Category                       0
Demographic                           0
# Total Cohort                        0
# Total Grads                         0
% of cohort Total Grads               0
# of cohort Total Grads               0
% of cohort Total Regents             0
% of grads  Total Regents             0
# of grads  Total Regents            10
% of cohort  Advanced Regents        10
% of grads  Advanced Regents         10
# of grads  Advanced Regents         10
% of cohort  Regents w/o Advanced    10
% of grads  Regents w/o Advanced     10
# of grads  Regents w/o Advanced      0
% of cohort Local                     0
% of grads Local                      0
# Still Enrolled                      0
% of cohort Still Enrolled            0
# Dropped Out                         0
% of cohort Dropped Out               0
dtype: int64

In [39]:
# Total number of missing NA
df.isnull().sum().sum()

60

In [40]:
# Fixing missing values. Missing values can be fixex by either encode  -1 or -9999, replace them with mean/median,
# fill them with 0, and so forth.
# The script below fixes the missing values in the dataset with -1
df.fillna(-1)

,Cohort Year,Cohort Category,Demographic,# Total Cohort,# Total Grads,% of cohort Total Grads,# of cohort Total Grads,% of cohort Total Regents,% of grads Total Regents,# of grads Total Regents,...,# of grads Advanced Regents,% of cohort Regents w/o Advanced,% of grads Regents w/o Advanced,# of grads Regents w/o Advanced,% of cohort Local,% of grads Local,# Still Enrolled,% of cohort Still Enrolled,# Dropped Out,% of cohort Dropped Out
0,2001,4 Year June,English Language Learner,10540,2791,26.5,992,9.0,35.5,315.0,...,677.0,6.4,24.3,1803,17.1,64.6,3895,37.0,3220,30.6
1,2001,5 Year June,English Language Learner,10540,3920,37.2,1233,11.7,31.5,371.0,...,862.0,8.2,22.0,2701,25.6,68.9,1516,14.4,4193,39.8
2,2001,6 Year,English Language Learner,10540,4296,40.8,1291,12.2,30.1,380.0,...,911.0,8.6,21.2,3028,28.7,70.5,655,6.2,4598,43.6
3,2002,4 Year June,English Language Learner,7454,1691,22.7,639,8.6,37.8,132.0,...,507.0,6.8,30.0,1062,14.2,62.8,3062,41.1,2330,31.3
4,2002,5 Year June,English Language Learner,7454,2354,31.6,794,10.7,33.7,176.0,...,618.0,8.3,26.3,1578,21.2,67.0,1457,19.5,3041,40.8
5,2002,6 Year,English Language Learner,7454,2729,36.6,856,11.5,31.4,185.0,...,671.0,9.0,24.6,1891,25.4,69.3,697,9.4,3356,45.0
6,2003,4 Year June,English Language Learner,8163,2052,25.1,909,11.1,44.3,290.0,...,619.0,7.6,30.2,1143,14.0,55.7,3360,41.2,2394,29.3
7,2003,5 Year June,English Language Learner,8163,3105,38.0,1159,14.2,37.3,358.0,...,801.0,9.8,25.8,1946,23.8,62.7,1327,16.3,3111,38.1
8,2003,6 Year,English Language Learner,8041,3394,42.2,1216,15.1,35.8,363.0,...,853.0,10.6,25.1,2178,27.1,64.2,570,7.1,3361,41.8
9,2004,4 Year June,English Language Learner,8486,3039,35.8,1504,17.7,49.5,487.0,...,1017.0,12.0,33.5,1535,18.1,50.5,3288,38.7,1840,21.7
10,2004,4 Year August,English Language Learner,8486,3404,40.1,1599,18.8,47.0,-1.0,...,-1.0,-1.0,-1.0,1809,21.3,53.1,2923,34.4,1840,21.7
11,2004,5 Year June,English Language Learner,8320,4065,48.9,1799,21.6,44.3,558.0,...,1241.0,14.9,30.5,2266,27.2,55.7,1151,13.8,2389,28.7
12,2004,6 Year,English Language Learner,8306,4394,52.9,1873,22.5,42.6,568.0,...,1305.0,15.7,29.7,2521,30.4,57.4,619,7.5,2710,32.6
13,2005,4 Year June,English Language Learner,8778,3481,39.7,1908,21.7,54.8,583.0,...,1325.0,15.1,38.1,1572,17.9,45.2,3060,34.9,1700,19.4
14,2005,4 Year August,English Language Learner,8778,3899,44.4,2015,23.0,51.7,594.0,...,1421.0,16.2,36.4,1883,21.5,48.3,2642,30.1,1700,19.4
15,2005,5 Year June,English Language Learner,8743,4546,52.0,2232,25.5,49.1,642.0,...,1590.0,18.2,35.0,2314,26.5,50.9,1016,11.6,2531,28.9
16,2005,6 Year,English Language Learner,8673,4852,55.9,2304,26.6,47.5,647.0,...,1657.0,19.1,34.2,2548,29.4,52.5,454,5.2,2711,31.3
17,2006,4 Year June,English Language Learner,9056,3755,41.5,2437,26.9,64.9,593.0,...,1844.0,20.4,49.1,1318,14.6,35.1,3002,33.1,1797,19.8
18,2006,4 Year August,English Language Learner,9056,4175,46.1,2573,28.4,61.6,608.0,...,1965.0,21.7,47.1,1602,17.7,38.4,2588,28.6,1791,19.8
19,2006,5 Year June,English Language Learner,9158,4775,52.1,2783,30.4,58.3,633.0,...,2150.0,23.5,45.0,1992,21.8,41.7,1095,12.0,2575,28.1
20,2006,5 Year August,English Language Learner,9158,4878,53.3,2812,30.7,57.6,633.0,...,2179.0,23.8,44.7,2066,22.6,42.4,1005,11.0,2559,27.9
21,2006,6 Year,English Language Learner,8829,5069,57.4,2867,32.5,56.6,633.0,...,2234.0,25.3,44.1,2202,24.9,43.4,341,3.9,2740,31.0
22,2007,4 Year June,English Language Learner,9444,3720,39.4,2765,29.3,74.3,562.0,...,2203.0,23.3,59.2,955,10.1,25.7,3407,36.1,1896,20.1
23,2007,4 Year August,English Language Learner,9444,4263,45.1,3013,31.9,70.7,575.0,...,2438.0,25.8,57.2,1250,13.2,29.3,2881,30.5,1883,19.9
24,2007,5 Year June,English Language Learner,9156,4824,52.7,3241,35.4,67.2,591.0,...,2650.0,28.9,54.9,1583,17.3,32.8,873,9.5,2856,31.2
25,2007,5 Year August,English Language Learner,9156,4977,54.4,3302,36.1,66.3,592.0,...,2710.0,29.6,54.5,1675,18.3,33.7,755,8.2,2825,30.9
26,2007,6 Year,English Language Learner,9134,5124,56.1,3386,37.1,66.1,593.0,...,2793.0,30.6,54.5,1738,19.0,33.9,416,4.6,2958,32.4
27,2008,4 Year June,English Language Learner,9174,3247,35.4,2933,32.0,90.3,615.0,...,2318.0,25.3,71.4,314,3.4,9.7,3715,40.5,1868,20.4
28,2008,4 Year August,English Language Learner,9174,3716,40.5,3318,36.2,89.3,624.0,...,2694.0,29.4,72.5,398,4.3,10.7,3257,35.5,1861,20.3
29,2008,5 Year June,English Language Learner,8914,4151,46.6,3654,41.0,88.0,635.0,...,3019.0,33.9,72.7,497,5.6,12.0,1700,19.1,2523,28.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,2005,4 Year June,Male,39096,20559,52.6,15565,39.8,75.7,5649.0,...,9916.0,25.4,48.2,4993,12.8,24.3,11196,28.6,5406,13.8
401,2005,4 Year August,Male,39096,22122,56.6,16299,41.7,73.7,5725.0,...,10574.0,27.0,47.8,5822,14.9,26.3,9634,24.6,5406,13.8
402,2005,5 Year June,Male,39470,24583,62.3,17374,44.0,70.7,5827.0,...,11547.0,29.3,47.0,7209,18.3,29.3,3992,10.1,8210,20.8
403,2005,6 Year,Male,39351,25912,65.8,17815,45.3,68.8,5831.0,...,11984.0,30.5,46.2,8097,20.6,31.2,2070,5.3,8719,22.2
404,2006,4 Year June,Male,39596,21840,55.2,17628,44.5,80.7,5787.0,...,11841.0,29.9,54.2,4212,10.6,19.3,10420,26.3,5452,13.8
405,2006,4 Year August,Male,39596,23597,59.6,18537,46.8,78.6,5855.0,...,12682.0,32.0,53.7,5060,12.8,21.4,8685,21.9,5431,13.7
406,2006,5 Year June,Male,40146,25751,64.1,19531,48.6,75.8,5904.0,...,13627.0,33.9,52.9,6220,15.5,24.2,3816,9.5,8078,20.1
407,2006,5 Year August,Male,40146,26194,65.2,19698,49.1,75.2,5904.0,...,13794.0,34.4,52.7,6496,16.2,24.8,3486,8.7,7946,19.8
408,2006,6 Year,Male,39415,27013,68.5,20014,50.8,74.1,5890.0,...,14124.0,35.8,52.3,6999,17.8,25.9,1514,3.8,8440,21.4
409,2007,4 Year June,Male,40519,22511,55.6,19458,48.0,86.4,5893.0,...,13565.0,33.5,60.3,3053,7.5,13.6,10785,26.6,5678,14.0
410,2007,4 Year August,Male,40519,24466,60.4,20636,50.9,84.3,5960.0,...,14676.0,36.2,60.0,3830,9.5,15.7,8906,22.0,5614,13.9
411,2007,5 Year June,Male,40166,26267,65.4,21476,53.5,81.8,5909.0,...,15567.0,38.8,59.3,4791,11.9,18.2,3346,8.3,8425,21.0
412,2007,5 Year August,Male,40166,26701,66.5,21691,54.0,81.2,5910.0,...,15781.0,39.3,59.1,5010,12.5,18.8,3017,7.5,8327,20.7
413,2007,6 Year,Male,40211,27588,68.6,22231,55.3,80.6,5980.0,...,16251.0,40.4,58.9,5357,13.3,19.4,1748,4.3,8647,21.5
414,2008,4 Year June,Male,40968,22758,55.6,21515,52.5,94.5,5997.0,...,15518.0,37.9,68.2,1243,3.0,5.5,11595,28.3,5345,13.0
415,2008,4 Year August,Male,40968,24534,59.9,23044,56.2,93.9,6052.0,...,16992.0,41.5,69.3,1490,3.6,6.1,9862,24.1,5326,13.0
416,2008,5 Year June,Male,40719,26461,65.0,24631,60.5,93.1,6082.0,...,18549.0,45.6,70.1,1830,4.5,6.9,4980,12.2,7281,17.9
417,2008,5 Year August,Male,40719,26938,66.2,25024,61.5,92.9,6089.0,...,18935.0,46.5,70.3,1914,4.7,7.1,4543,11.2,7252,17.8
418,2008,6 Year,Male,40612,27810,68.5,25652,63.2,92.2,6091.0,...,19561.0,48.2,70.3,2158,5.3,7.8,2563,6.3,7806,19.2
419,2009,4 Year June,Male,40139,22565,56.2,21302,53.1,94.4,6034.0,...,15268.0,38.0,67.7,1263,3.1,5.6,11552,28.8,4845,12.1
420,2009,4 Year August,Male,40139,24573,61.2,23046,57.4,93.8,6104.0,...,16942.0,42.2,68.9,1527,3.8,6.2,9575,23.9,4843,12.1
421,2009,5 Year June,Male,39880,26740,67.1,24783,62.1,92.7,6135.0,...,18648.0,46.8,69.7,1957,4.9,7.3,4926,12.4,6735,16.9
422,2009,5 Year August,Male,39880,27224,68.3,25177,63.1,92.5,6138.0,...,19039.0,47.7,69.9,2047,5.1,7.5,4466,11.2,6719,16.8
423,2009,6 Year,Male,39842,28173,70.7,25874,64.9,91.8,6140.0,...,19734.0,49.5,70.0,2299,5.8,8.2,2657,6.7,7406,18.6
424,2010,4 Year June,Male,38680,23061,59.6,21471,55.5,93.1,6051.0,...,15420.0,39.9,66.9,1590,4.1,6.9,10575,27.3,4133,10.7
425,2010,4 Year August,Male,38680,24845,64.2,22983,59.4,92.5,6134.0,...,16849.0,43.6,67.8,1862,4.8,7.5,8799,22.7,4131,10.7
426,2010,5 Year June,Male,38495,26876,69.8,24537,63.7,91.3,6158.0,...,18379.0,47.7,68.4,2339,6.1,8.7,4364,11.3,5963,15.5
427,2010,5 Year August,Male,38495,27231,70.7,24810,64.4,91.1,6160.0,...,18650.0,48.4,68.5,2421,6.3,8.9,4021,10.4,5953,15.5
428,2011,4 Year June,Male,38220,23581,61.7,22165,58.0,94.0,6285.0,...,15880.0,41.5,67.3,1416,3.7,6.0,9805,25.7,3926,10.3
429,2011,4 Year August,Male,38220,24973,65.3,23299,61.0,93.3,6336.0,...,16963.0,44.4,67.9,1674,4.4,6.7,8423,22.0,3924,10.3

In [41]:
# Find duplicates in the dataset.
df.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
Length: 430, dtype: bool

In [42]:
# Total number of duplicates
df.duplicated().sum()

0

In [ ]:
# The total numbers of duplicates returns 0 as output, which means the data does not have duplicate values.
# If duplicate values were present in the data, one of the following techniques would be used to remove them.
# 1- Naive method
# 2- list comprehension 
# 3- The set() method
# 4- list comprehension + enumerate() method
# 5- collections.OrderedDict.fromkeys() method

In [ ]:
# Conduct Fuzzy Matching
#  (if you donâ€™t have an obvious example to do this within your data, create categories and use
# Fuzzy Matching to lump data together) (Data Wrangling with Python pg. 179 â€“ 188)

In [43]:
# It does not seem obvious to conduct fuzzy matching within the data, so I create categories to conduct it.
# See below for the categories created.
from fuzzywuzzy import fuzz
Str1 = "Amazon Inc."
Str2 = "amazon Inc"
Ratio = fuzz.ratio(Str1.lower(),Str2.lower())
print(Ratio)

95

C:\Users\cherf001\Anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [44]:
Str1 = "Las Vegas, Nevada"
Str2 = "Nevada"
Ratio = fuzz.ratio(Str1.lower(),Str2.lower())
Partial_Ratio = fuzz.partial_ratio(Str1.lower(),Str2.lower())
print(Ratio)
print(Partial_Ratio)

52
100

In [ ]:
# Using Python, submit your results via your notebook or export your code and submit via the assignment link. 
# You must show your code and work for full credit.

In [ ]:
# A 250-word paper summarizing your steps and any challenges you ran into during the project.
# You should also outline any decisions you had to make while transforming the data 
# (for example, if you decided to remove duplicates, how did you arrive at that decision?).